### ISSUE TITLE
Add gomodule support

### ISSUE THREAD

**Issue by lu4p** [cretz/tor-static#29]

**Comment by cretz** [comment]
Can you clarify this request? The only Go in this repository (not counting the test) is a build script which is just a cross-platform Makefile of sorts that can be executed with `go run` and only uses stdlib packages. This repository is for building the Tor lib statically that can be used in any project, not just Go ones...it won't be `go get`able because it has to do too much on build and has too many prereqs.

**Comment by lu4p** [comment]
Looked into it a little more the tor-static files just need to go into this directory `~/go/pkg/mod/github.com/cretz/tor-static` to support go modules

**Comment by lu4p** [comment]
Submitted a pull request to bine https://github.com/cretz/bine/pull/34 to make this clear in the documentation.
